export interface Country {
  id: string;
  name: string;
  code: string;
  phonePrefix: string;
  flag: string;
  currency: string;
  cities?: City[]; // Make cities optional as not all countries will have them detailed
}

export interface City {
  name: string;
  communes?: string[];
}

export const ALL_COUNTRIES: Country[] = [
  {
    id: "1",
    name: "Afghanistan",
    code: "AF",
    phonePrefix: "+93",
    flag: "🇦🇫",
    currency: "AFN",
  },
  {
    id: "2",
    name: "Albania",
    code: "AL",
    phonePrefix: "+355",
    flag: "🇦🇱",
    currency: "ALL",
  },
  {
    id: "3",
    name: "Algeria",
    code: "DZ",
    phonePrefix: "+213",
    flag: "🇩🇿",
    currency: "DZD",
  },
  {
    id: "4",
    name: "Andorra",
    code: "AD",
    phonePrefix: "+376",
    flag: "🇦🇩",
    currency: "EUR",
  },
  {
    id: "5",
    name: "Angola",
    code: "AO",
    phonePrefix: "+244",
    flag: "🇦🇴",
    currency: "AOA",
  },
  {
    id: "6",
    name: "Antigua and Barbuda",
    code: "AG",
    phonePrefix: "+1-268",
    flag: "🇦🇬",
    currency: "XCD",
  },
  {
    id: "7",
    name: "Argentina",
    code: "AR",
    phonePrefix: "+54",
    flag: "🇦🇷",
    currency: "ARS",
  },
  {
    id: "8",
    name: "Armenia",
    code: "AM",
    phonePrefix: "+374",
    flag: "🇦🇲",
    currency: "AMD",
  },
  {
    id: "9",
    name: "Australia",
    code: "AU",
    phonePrefix: "+61",
    flag: "🇦🇺",
    currency: "AUD",
  },
  {
    id: "10",
    name: "Austria",
    code: "AT",
    phonePrefix: "+43",
    flag: "🇦🇹",
    currency: "EUR",
  },
  {
    id: "11",
    name: "Azerbaijan",
    code: "AZ",
    phonePrefix: "+994",
    flag: "🇦🇿",
    currency: "AZN",
  },
  {
    id: "12",
    name: "Bahamas",
    code: "BS",
    phonePrefix: "+1-242",
    flag: "🇧🇸",
    currency: "BSD",
  },
  {
    id: "13",
    name: "Bahrain",
    code: "BH",
    phonePrefix: "+973",
    flag: "🇧🇭",
    currency: "BHD",
  },
  {
    id: "14",
    name: "Bangladesh",
    code: "BD",
    phonePrefix: "+880",
    flag: "🇧🇩",
    currency: "BDT",
  },
  {
    id: "15",
    name: "Barbados",
    code: "BB",
    phonePrefix: "+1-246",
    flag: "🇧🇧",
    currency: "BBD",
  },
  {
    id: "16",
    name: "Belarus",
    code: "BY",
    phonePrefix: "+375",
    flag: "🇧🇾",
    currency: "BYN",
  },
  {
    id: "17",
    name: "Belgium",
    code: "BE",
    phonePrefix: "+32",
    flag: "🇧🇪",
    currency: "EUR",
  },
  {
    id: "18",
    name: "Belize",
    code: "BZ",
    phonePrefix: "+501",
    flag: "🇧🇿",
    currency: "BZD",
  },
  {
    id: "19",
    name: "Benin",
    code: "BJ",
    phonePrefix: "+229",
    flag: "🇧🇯",
    currency: "XOF",
    cities: [
      {
        name: "Cotonou",
        communes: [
          "1er Arrondissement",
          "2ème Arrondissement",
          "3ème Arrondissement",
          "4ème Arrondissement",
          "5ème Arrondissement",
          "6ème Arrondissement",
          "7ème Arrondissement",
          "8ème Arrondissement",
          "9ème Arrondissement",
          "10ème Arrondissement",
          "11ème Arrondissement",
          "12ème Arrondissement",
          "13ème Arrondissement",
        ],
      },
      {
        name: "Porto-Novo",
        communes: ["Porto-Novo Centre", "Porto-Novo Nord", "Porto-Novo Sud"],
      },
      {
        name: "Parakou",
        communes: ["Parakou Centre", "Parakou Nord", "Parakou Sud"],
      },
      { name: "Djougou", communes: ["Djougou Centre", "Djougou Nord"] },
      { name: "Bohicon" },
      { name: "Kandi" },
      { name: "Lokossa" },
      { name: "Ouidah" },
      { name: "Abomey" },
    ],
  },
  {
    id: "20",
    name: "Bhutan",
    code: "BT",
    phonePrefix: "+975",
    flag: "🇧🇹",
    currency: "BTN",
  },
  {
    id: "21",
    name: "Bolivia",
    code: "BO",
    phonePrefix: "+591",
    flag: "🇧🇴",
    currency: "BOB",
  },
  {
    id: "22",
    name: "Bosnia and Herzegovina",
    code: "BA",
    phonePrefix: "+387",
    flag: "🇧🇦",
    currency: "BAM",
  },
  {
    id: "23",
    name: "Botswana",
    code: "BW",
    phonePrefix: "+267",
    flag: "🇧🇼",
    currency: "BWP",
  },
  {
    id: "24",
    name: "Brazil",
    code: "BR",
    phonePrefix: "+55",
    flag: "🇧🇷",
    currency: "BRL",
  },
  {
    id: "25",
    name: "Brunei",
    code: "BN",
    phonePrefix: "+673",
    flag: "🇧🇳",
    currency: "BND",
  },
  {
    id: "26",
    name: "Bulgaria",
    code: "BG",
    phonePrefix: "+359",
    flag: "🇧🇬",
    currency: "BGN",
  },
  {
    id: "27",
    name: "Burkina Faso",
    code: "BF",
    phonePrefix: "+226",
    flag: "🇧🇫",
    currency: "XOF",
    cities: [
      {
        name: "Ouagadougou",
        communes: [
          "Baskuy",
          "Bogodogo",
          "Boulmiougou",
          "Nongremassom",
          "Sig-Nonghin",
        ],
      },
      {
        name: "Bobo-Dioulasso",
        communes: [
          "Do",
          "Dafra",
          "Konsa",
          "Secteur 1",
          "Secteur 2",
          "Secteur 3",
        ],
      },
      { name: "Koudougou", communes: ["Koudougou Centre", "Koudougou Nord"] },
      {
        name: "Ouahigouya",
        communes: ["Ouahigouya Centre", "Ouahigouya Nord"],
      },
      { name: "Banfora" },
      { name: "Kaya" },
      { name: "Tenkodogo" },
      { name: "Fada N'Gourma" },
    ],
  },
  {
    id: "28",
    name: "Burundi",
    code: "BI",
    phonePrefix: "+257",
    flag: "🇧🇮",
    currency: "BIF",
  },
  {
    id: "29",
    name: "Cabo Verde",
    code: "CV",
    phonePrefix: "+238",
    flag: "🇨🇻",
    currency: "CVE",
  },
  {
    id: "30",
    name: "Cambodia",
    code: "KH",
    phonePrefix: "+855",
    flag: "🇰🇭",
    currency: "KHR",
  },
  {
    id: "31",
    name: "Cameroon",
    code: "CM",
    phonePrefix: "+237",
    flag: "🇨🇲",
    currency: "XAF",
    cities: [
      {
        name: "Yaoundé",
        communes: [
          "Yaoundé I",
          "Yaoundé II",
          "Yaoundé III",
          "Yaoundé IV",
          "Yaoundé V",
          "Yaoundé VI",
          "Yaoundé VII",
        ],
      },
      {
        name: "Douala",
        communes: [
          "Douala I",
          "Douala II",
          "Douala III",
          "Douala IV",
          "Douala V",
        ],
      },
      { name: "Garoua" },
      { name: "Bamenda" },
      { name: "Maroua" },
      { name: "Bafoussam" },
    ],
  },
  {
    id: "32",
    name: "Canada",
    code: "CA",
    phonePrefix: "+1",
    flag: "🇨🇦",
    currency: "CAD",
  },
  {
    id: "33",
    name: "Central African Republic",
    code: "CF",
    phonePrefix: "+236",
    flag: "🇨🇫",
    currency: "XAF",
  },
  {
    id: "34",
    name: "Chad",
    code: "TD",
    phonePrefix: "+235",
    flag: "🇹🇩",
    currency: "XAF",
  },
  {
    id: "35",
    name: "Chile",
    code: "CL",
    phonePrefix: "+56",
    flag: "🇨🇱",
    currency: "CLP",
  },
  {
    id: "36",
    name: "China",
    code: "CN",
    phonePrefix: "+86",
    flag: "🇨🇳",
    currency: "CNY",
  },
  {
    id: "37",
    name: "Colombia",
    code: "CO",
    phonePrefix: "+57",
    flag: "🇨🇴",
    currency: "COP",
  },
  {
    id: "38",
    name: "Comoros",
    code: "KM",
    phonePrefix: "+269",
    flag: "🇰🇲",
    currency: "KMF",
  },
  {
    id: "39",
    name: "Congo (DRC)",
    code: "CD",
    phonePrefix: "+243",
    flag: "🇨🇩",
    currency: "CDF",
  },
  {
    id: "40",
    name: "Congo (Republic)",
    code: "CG",
    phonePrefix: "+242",
    flag: "🇨🇬",
    currency: "XAF",
  },
  {
    id: "41",
    name: "Costa Rica",
    code: "CR",
    phonePrefix: "+506",
    flag: "🇨🇷",
    currency: "CRC",
  },
  {
    id: "42",
    name: "Côte d'Ivoire",
    code: "CI",
    phonePrefix: "+225",
    flag: "🇨🇮",
    currency: "XOF",
    cities: [
      {
        name: "Abidjan",
        communes: [
          "Cocody",
          "Yopougon",
          "Adjamé",
          "Plateau",
          "Marcory",
          "Treichville",
          "Koumassi",
          "Port-Bouët",
          "Abobo",
          "Attécoubé",
        ],
      },
      {
        name: "Bouaké",
        communes: ["Bouaké Centre", "Bouaké Nord", "Bouaké Sud"],
      },
      { name: "Daloa", communes: ["Daloa Centre", "Daloa Nord", "Daloa Sud"] },
      {
        name: "Yamoussoukro",
        communes: [
          "Yamoussoukro Centre",
          "Yamoussoukro Nord",
          "Yamoussoukro Sud",
        ],
      },
      { name: "San-Pédro", communes: ["San-Pédro Centre", "San-Pédro Port"] },
      { name: "Korhogo" },
      { name: "Man" },
      { name: "Gagnoa" },
      { name: "Divo" },
      { name: "Anyama" },
    ],
  },
  {
    id: "43",
    name: "Croatia",
    code: "HR",
    phonePrefix: "+385",
    flag: "🇭🇷",
    currency: "EUR",
  },
  {
    id: "44",
    name: "Cuba",
    code: "CU",
    phonePrefix: "+53",
    flag: "🇨🇺",
    currency: "CUP",
  },
  {
    id: "45",
    name: "Cyprus",
    code: "CY",
    phonePrefix: "+357",
    flag: "🇨🇾",
    currency: "EUR",
  },
  {
    id: "46",
    name: "Czech Republic",
    code: "CZ",
    phonePrefix: "+420",
    flag: "🇨🇿",
    currency: "CZK",
  },
  {
    id: "47",
    name: "Denmark",
    code: "DK",
    phonePrefix: "+45",
    flag: "🇩🇰",
    currency: "DKK",
  },
  {
    id: "48",
    name: "Djibouti",
    code: "DJ",
    phonePrefix: "+253",
    flag: "🇩🇯",
    currency: "DJF",
  },
  {
    id: "49",
    name: "Dominica",
    code: "DM",
    phonePrefix: "+1-767",
    flag: "🇩🇲",
    currency: "XCD",
  },
  {
    id: "50",
    name: "Dominican Republic",
    code: "DO",
    phonePrefix: "+1-809",
    flag: "🇩🇴",
    currency: "DOP",
  },
  {
    id: "51",
    name: "East Timor",
    code: "TL",
    phonePrefix: "+670",
    flag: "🇹🇱",
    currency: "USD",
  },
  {
    id: "52",
    name: "Ecuador",
    code: "EC",
    phonePrefix: "+593",
    flag: "🇪🇨",
    currency: "USD",
  },
  {
    id: "53",
    name: "Egypt",
    code: "EG",
    phonePrefix: "+20",
    flag: "🇪🇬",
    currency: "EGP",
  },
  {
    id: "54",
    name: "El Salvador",
    code: "SV",
    phonePrefix: "+503",
    flag: "🇸🇻",
    currency: "USD",
  },
  {
    id: "55",
    name: "Equatorial Guinea",
    code: "GQ",
    phonePrefix: "+240",
    flag: "🇬🇶",
    currency: "XAF",
  },
  {
    id: "56",
    name: "Eritrea",
    code: "ER",
    phonePrefix: "+291",
    flag: "🇪🇷",
    currency: "ERN",
  },
  {
    id: "57",
    name: "Estonia",
    code: "EE",
    phonePrefix: "+372",
    flag: "🇪🇪",
    currency: "EUR",
  },
  {
    id: "58",
    name: "Eswatini",
    code: "SZ",
    phonePrefix: "+268",
    flag: "🇸🇿",
    currency: "SZL",
  },
  {
    id: "59",
    name: "Ethiopia",
    code: "ET",
    phonePrefix: "+251",
    flag: "🇪🇹",
    currency: "ETB",
  },
  {
    id: "60",
    name: "Fiji",
    code: "FJ",
    phonePrefix: "+679",
    flag: "🇫🇯",
    currency: "FJD",
  },
  {
    id: "61",
    name: "Finland",
    code: "FI",
    phonePrefix: "+358",
    flag: "🇫🇮",
    currency: "EUR",
  },
  {
    id: "62",
    name: "France",
    code: "FR",
    phonePrefix: "+33",
    flag: "🇫🇷",
    currency: "EUR",
  },
  {
    id: "63",
    name: "Gabon",
    code: "GA",
    phonePrefix: "+241",
    flag: "🇬🇦",
    currency: "XAF",
  },
  {
    id: "64",
    name: "Gambia",
    code: "GM",
    phonePrefix: "+220",
    flag: "🇬🇲",
    currency: "GMD",
  },
  {
    id: "65",
    name: "Georgia",
    code: "GE",
    phonePrefix: "+995",
    flag: "🇬🇪",
    currency: "GEL",
  },
  {
    id: "66",
    name: "Germany",
    code: "DE",
    phonePrefix: "+49",
    flag: "🇩🇪",
    currency: "EUR",
  },
  {
    id: "67",
    name: "Ghana",
    code: "GH",
    phonePrefix: "+233",
    flag: "🇬🇭",
    currency: "GHS",
    cities: [
      {
        name: "Accra",
        communes: [
          "Accra Metropolitan",
          "Tema",
          "Ga East",
          "Ga West",
          "Ga South",
        ],
      },
      {
        name: "Kumasi",
        communes: ["Kumasi Metropolitan", "Oforikrom", "Asokwa", "Subin"],
      },
      { name: "Tamale" },
      { name: "Cape Coast" },
      { name: "Sekondi-Takoradi" },
      { name: "Ho" },
      { name: "Koforidua" },
    ],
  },
  {
    id: "68",
    name: "Greece",
    code: "GR",
    phonePrefix: "+30",
    flag: "🇬🇷",
    currency: "EUR",
  },
  {
    id: "69",
    name: "Grenada",
    code: "GD",
    phonePrefix: "+1-473",
    flag: "🇬🇩",
    currency: "XCD",
  },
  {
    id: "70",
    name: "Guatemala",
    code: "GT",
    phonePrefix: "+502",
    flag: "🇬🇹",
    currency: "GTQ",
  },
  {
    id: "71",
    name: "Guinea",
    code: "GN",
    phonePrefix: "+224",
    flag: "🇬🇳",
    currency: "GNF",
  },
  {
    id: "72",
    name: "Guinea-Bissau",
    code: "GW",
    phonePrefix: "+245",
    flag: "🇬🇼",
    currency: "XOF",
  },
  {
    id: "73",
    name: "Guyana",
    code: "GY",
    phonePrefix: "+592",
    flag: "🇬🇾",
    currency: "GYD",
  },
  {
    id: "74",
    name: "Haiti",
    code: "HT",
    phonePrefix: "+509",
    flag: "🇭🇹",
    currency: "HTG",
  },
  {
    id: "75",
    name: "Honduras",
    code: "HN",
    phonePrefix: "+504",
    flag: "🇭🇳",
    currency: "HNL",
  },
  {
    id: "76",
    name: "Hungary",
    code: "HU",
    phonePrefix: "+36",
    flag: "🇭🇺",
    currency: "HUF",
  },
  {
    id: "77",
    name: "Iceland",
    code: "IS",
    phonePrefix: "+354",
    flag: "🇮🇸",
    currency: "ISK",
  },
  {
    id: "78",
    name: "India",
    code: "IN",
    phonePrefix: "+91",
    flag: "🇮🇳",
    currency: "INR",
  },
  {
    id: "79",
    name: "Indonesia",
    code: "ID",
    phonePrefix: "+62",
    flag: "🇮🇩",
    currency: "IDR",
  },
  {
    id: "80",
    name: "Iran",
    code: "IR",
    phonePrefix: "+98",
    flag: "🇮🇷",
    currency: "IRR",
  },
  {
    id: "81",
    name: "Iraq",
    code: "IQ",
    phonePrefix: "+964",
    flag: "🇮🇶",
    currency: "IQD",
  },
  {
    id: "82",
    name: "Ireland",
    code: "IE",
    phonePrefix: "+353",
    flag: "🇮🇪",
    currency: "EUR",
  },
  {
    id: "83",
    name: "Israel",
    code: "IL",
    phonePrefix: "+972",
    flag: "🇮🇱",
    currency: "ILS",
  },
  {
    id: "84",
    name: "Italy",
    code: "IT",
    phonePrefix: "+39",
    flag: "🇮🇹",
    currency: "EUR",
  },
  {
    id: "85",
    name: "Jamaica",
    code: "JM",
    phonePrefix: "+1-876",
    flag: "🇯🇲",
    currency: "JMD",
  },
  {
    id: "86",
    name: "Japan",
    code: "JP",
    phonePrefix: "+81",
    flag: "🇯🇵",
    currency: "JPY",
  },
  {
    id: "87",
    name: "Jordan",
    code: "JO",
    phonePrefix: "+962",
    flag: "🇯🇴",
    currency: "JOD",
  },
  {
    id: "88",
    name: "Kazakhstan",
    code: "KZ",
    phonePrefix: "+7",
    flag: "🇰🇿",
    currency: "KZT",
  },
  {
    id: "89",
    name: "Kenya",
    code: "KE",
    phonePrefix: "+254",
    flag: "🇰🇪",
    currency: "KES",
  },
  {
    id: "90",
    name: "Kiribati",
    code: "KI",
    phonePrefix: "+686",
    flag: "🇰🇮",
    currency: "AUD",
  },
  {
    id: "91",
    name: "North Korea",
    code: "KP",
    phonePrefix: "+850",
    flag: "🇰🇵",
    currency: "KPW",
  },
  {
    id: "92",
    name: "South Korea",
    code: "KR",
    phonePrefix: "+82",
    flag: "🇰🇷",
    currency: "KRW",
  },
  {
    id: "93",
    name: "Kuwait",
    code: "KW",
    phonePrefix: "+965",
    flag: "🇰🇼",
    currency: "KWD",
  },
  {
    id: "94",
    name: "Kyrgyzstan",
    code: "KG",
    phonePrefix: "+996",
    flag: "🇰🇬",
    currency: "KGS",
  },
  {
    id: "95",
    name: "Laos",
    code: "LA",
    phonePrefix: "+856",
    flag: "🇱🇦",
    currency: "LAK",
  },
  {
    id: "96",
    name: "Latvia",
    code: "LV",
    phonePrefix: "+371",
    flag: "🇱🇻",
    currency: "EUR",
  },
  {
    id: "97",
    name: "Lebanon",
    code: "LB",
    phonePrefix: "+961",
    flag: "🇱🇧",
    currency: "LBP",
  },
  {
    id: "98",
    name: "Lesotho",
    code: "LS",
    phonePrefix: "+266",
    flag: "🇱🇸",
    currency: "LSL",
  },
  {
    id: "99",
    name: "Liberia",
    code: "LR",
    phonePrefix: "+231",
    flag: "🇱🇷",
    currency: "LRD",
  },
  {
    id: "100",
    name: "Libya",
    code: "LY",
    phonePrefix: "+218",
    flag: "🇱🇾",
    currency: "LYD",
  },
  {
    id: "101",
    name: "Liechtenstein",
    code: "LI",
    phonePrefix: "+423",
    flag: "🇱🇮",
    currency: "CHF",
  },
  {
    id: "102",
    name: "Lithuania",
    code: "LT",
    phonePrefix: "+370",
    flag: "🇱🇹",
    currency: "EUR",
  },
  {
    id: "103",
    name: "Luxembourg",
    code: "LU",
    phonePrefix: "+352",
    flag: "🇱🇺",
    currency: "EUR",
  },
  {
    id: "104",
    name: "Madagascar",
    code: "MG",
    phonePrefix: "+261",
    flag: "🇲🇬",
    currency: "MGA",
  },
  {
    id: "105",
    name: "Malawi",
    code: "MW",
    phonePrefix: "+265",
    flag: "🇲🇼",
    currency: "MWK",
  },
  {
    id: "106",
    name: "Malaysia",
    code: "MY",
    phonePrefix: "+60",
    flag: "🇲🇾",
    currency: "MYR",
  },
  {
    id: "107",
    name: "Maldives",
    code: "MV",
    phonePrefix: "+960",
    flag: "🇲🇻",
    currency: "MVR",
  },
  {
    id: "108",
    name: "Mali",
    code: "ML",
    phonePrefix: "+223",
    flag: "🇲🇱",
    currency: "XOF",
    cities: [
      {
        name: "Bamako",
        communes: [
          "Commune I",
          "Commune II",
          "Commune III",
          "Commune IV",
          "Commune V",
          "Commune VI",
        ],
      },
      {
        name: "Sikasso",
        communes: ["Sikasso Centre", "Sikasso Nord", "Sikasso Sud"],
      },
      { name: "Mopti", communes: ["Mopti Centre", "Mopti Nord"] },
      { name: "Ségou", communes: ["Ségou Centre", "Ségou Nord", "Ségou Sud"] },
      { name: "Kayes", communes: ["Kayes Centre", "Kayes Nord"] },
      { name: "Koutiala" },
      { name: "Gao" },
      { name: "Tombouctou" },
      { name: "Kidal" },
    ],
  },
  {
    id: "109",
    name: "Malta",
    code: "MT",
    phonePrefix: "+356",
    flag: "🇲🇹",
    currency: "EUR",
  },
  {
    id: "110",
    name: "Marshall Islands",
    code: "MH",
    phonePrefix: "+692",
    flag: "🇲🇭",
    currency: "USD",
  },
  {
    id: "111",
    name: "Mauritania",
    code: "MR",
    phonePrefix: "+222",
    flag: "🇲🇷",
    currency: "MRU",
  },
  {
    id: "112",
    name: "Mauritius",
    code: "MU",
    phonePrefix: "+230",
    flag: "🇲🇺",
    currency: "MUR",
  },
  {
    id: "113",
    name: "Mexico",
    code: "MX",
    phonePrefix: "+52",
    flag: "🇲🇽",
    currency: "MXN",
  },
  {
    id: "114",
    name: "Micronesia",
    code: "FM",
    phonePrefix: "+691",
    flag: "🇫🇲",
    currency: "USD",
  },
  {
    id: "115",
    name: "Moldova",
    code: "MD",
    phonePrefix: "+373",
    flag: "🇲🇩",
    currency: "MDL",
  },
  {
    id: "116",
    name: "Monaco",
    code: "MC",
    phonePrefix: "+377",
    flag: "🇲🇨",
    currency: "EUR",
  },
  {
    id: "117",
    name: "Mongolia",
    code: "MN",
    phonePrefix: "+976",
    flag: "🇲🇳",
    currency: "MNT",
  },
  {
    id: "118",
    name: "Montenegro",
    code: "ME",
    phonePrefix: "+382",
    flag: "🇲🇪",
    currency: "EUR",
  },
  {
    id: "119",
    name: "Morocco",
    code: "MA",
    phonePrefix: "+212",
    flag: "🇲🇦",
    currency: "MAD",
  },
  {
    id: "120",
    name: "Mozambique",
    code: "MZ",
    phonePrefix: "+258",
    flag: "🇲🇿",
    currency: "MZN",
  },
  {
    id: "121",
    name: "Myanmar",
    code: "MM",
    phonePrefix: "+95",
    flag: "🇲🇲",
    currency: "MMK",
  },
  {
    id: "122",
    name: "Namibia",
    code: "NA",
    phonePrefix: "+264",
    flag: "🇳🇦",
    currency: "NAD",
  },
  {
    id: "123",
    name: "Nauru",
    code: "NR",
    phonePrefix: "+674",
    flag: "🇳🇷",
    currency: "AUD",
  },
  {
    id: "124",
    name: "Nepal",
    code: "NP",
    phonePrefix: "+977",
    flag: "🇳🇵",
    currency: "NPR",
  },
  {
    id: "125",
    name: "Netherlands",
    code: "NL",
    phonePrefix: "+31",
    flag: "🇳🇱",
    currency: "EUR",
  },
  {
    id: "126",
    name: "New Zealand",
    code: "NZ",
    phonePrefix: "+64",
    flag: "🇳🇿",
    currency: "NZD",
  },
  {
    id: "127",
    name: "Nicaragua",
    code: "NI",
    phonePrefix: "+505",
    flag: "🇳🇮",
    currency: "NIO",
  },
  {
    id: "128",
    name: "Niger",
    code: "NE",
    phonePrefix: "+227",
    flag: "🇳🇪",
    currency: "XOF",
    cities: [
      {
        name: "Niamey",
        communes: [
          "Niamey I",
          "Niamey II",
          "Niamey III",
          "Niamey IV",
          "Niamey V",
        ],
      },
      { name: "Zinder" },
      { name: "Maradi" },
      { name: "Agadez" },
      { name: "Tahoua" },
      { name: "Dosso" },
    ],
  },
  {
    id: "129",
    name: "Nigeria",
    code: "NG",
    phonePrefix: "+234",
    flag: "🇳🇬",
    currency: "NGN",
    cities: [
      {
        name: "Lagos",
        communes: [
          "Lagos Island",
          "Lagos Mainland",
          "Surulere",
          "Ikeja",
          "Eti-Osa",
          "Kosofe",
          "Mushin",
          "Oshodi-Isolo",
          "Shomolu",
          "Alimosho",
        ],
      },
      {
        name: "Abuja",
        communes: ["Garki", "Wuse", "Maitama", "Asokoro", "Gwarinpa", "Kubwa"],
      },
      { name: "Kano" },
      { name: "Ibadan" },
      { name: "Port Harcourt" },
      { name: "Benin City" },
      { name: "Kaduna" },
    ],
  },
  {
    id: "130",
    name: "North Macedonia",
    code: "MK",
    phonePrefix: "+389",
    flag: "🇲🇰",
    currency: "MKD",
  },
  {
    id: "131",
    name: "Norway",
    code: "NO",
    phonePrefix: "+47",
    flag: "🇳🇴",
    currency: "NOK",
  },
  {
    id: "132",
    name: "Oman",
    code: "OM",
    phonePrefix: "+968",
    flag: "🇴🇲",
    currency: "OMR",
  },
  {
    id: "133",
    name: "Pakistan",
    code: "PK",
    phonePrefix: "+92",
    flag: "🇵🇰",
    currency: "PKR",
  },
  {
    id: "134",
    name: "Palau",
    code: "PW",
    phonePrefix: "+680",
    flag: "🇵🇼",
    currency: "USD",
  },
  {
    id: "135",
    name: "Palestine",
    code: "PS",
    phonePrefix: "+970",
    flag: "🇵🇸",
    currency: "ILS",
  },
  {
    id: "136",
    name: "Panama",
    code: "PA",
    phonePrefix: "+507",
    flag: "🇵🇦",
    currency: "PAB",
  },
  {
    id: "137",
    name: "Papua New Guinea",
    code: "PG",
    phonePrefix: "+675",
    flag: "🇵🇬",
    currency: "PGK",
  },
  {
    id: "138",
    name: "Paraguay",
    code: "PY",
    phonePrefix: "+595",
    flag: "🇵🇾",
    currency: "PYG",
  },
  {
    id: "139",
    name: "Peru",
    code: "PE",
    phonePrefix: "+51",
    flag: "🇵🇪",
    currency: "PEN",
  },
  {
    id: "140",
    name: "Philippines",
    code: "PH",
    phonePrefix: "+63",
    flag: "🇵🇭",
    currency: "PHP",
  },
  {
    id: "141",
    name: "Poland",
    code: "PL",
    phonePrefix: "+48",
    flag: "🇵🇱",
    currency: "PLN",
  },
  {
    id: "142",
    name: "Portugal",
    code: "PT",
    phonePrefix: "+351",
    flag: "🇵🇹",
    currency: "EUR",
  },
  {
    id: "143",
    name: "Qatar",
    code: "QA",
    phonePrefix: "+974",
    flag: "🇶🇦",
    currency: "QAR",
  },
  {
    id: "144",
    name: "Romania",
    code: "RO",
    phonePrefix: "+40",
    flag: "🇷🇴",
    currency: "RON",
  },
  {
    id: "145",
    name: "Russia",
    code: "RU",
    phonePrefix: "+7",
    flag: "🇷🇺",
    currency: "RUB",
  },
  {
    id: "146",
    name: "Rwanda",
    code: "RW",
    phonePrefix: "+250",
    flag: "🇷🇼",
    currency: "RWF",
  },
  {
    id: "147",
    name: "Saint Kitts and Nevis",
    code: "KN",
    phonePrefix: "+1-869",
    flag: "🇰🇳",
    currency: "XCD",
  },
  {
    id: "148",
    name: "Saint Lucia",
    code: "LC",
    phonePrefix: "+1-758",
    flag: "🇱🇨",
    currency: "XCD",
  },
  {
    id: "149",
    name: "Saint Vincent and the Grenadines",
    code: "VC",
    phonePrefix: "+1-784",
    flag: "🇻🇨",
    currency: "XCD",
  },
  {
    id: "150",
    name: "Samoa",
    code: "WS",
    phonePrefix: "+685",
    flag: "🇼🇸",
    currency: "WST",
  },
  {
    id: "151",
    name: "San Marino",
    code: "SM",
    phonePrefix: "+378",
    flag: "🇸🇲",
    currency: "EUR",
  },
  {
    id: "152",
    name: "Sao Tome and Principe",
    code: "ST",
    phonePrefix: "+239",
    flag: "🇸🇹",
    currency: "STN",
  },
  {
    id: "153",
    name: "Saudi Arabia",
    code: "SA",
    phonePrefix: "+966",
    flag: "🇸🇦",
    currency: "SAR",
  },
  {
    id: "154",
    name: "Senegal",
    code: "SN",
    phonePrefix: "+221",
    flag: "🇸🇳",
    currency: "XOF",
    cities: [
      {
        name: "Dakar",
        communes: [
          "Plateau",
          "Médina",
          "Fann",
          "Mermoz",
          "Ouakam",
          "Yoff",
          "Ngor",
          "Almadies",
          "Grand Yoff",
          "Parcelles Assainies",
        ],
      },
      {
        name: "Thiès",
        communes: ["Thiès Nord", "Thiès Sud", "Thiès Est", "Thiès Ouest"],
      },
      {
        name: "Kaolack",
        communes: ["Kaolack Nord", "Kaolack Sud", "Médina Baye"],
      },
      {
        name: "Saint-Louis",
        communes: ["Saint-Louis Nord", "Saint-Louis Sud", "Sor"],
      },
      { name: "Ziguinchor", communes: ["Ziguinchor Nord", "Ziguinchor Sud"] },
      { name: "Diourbel", communes: ["Diourbel Nord", "Diourbel Sud"] },
      { name: "Louga", communes: ["Louga Nord", "Louga Sud"] },
      { name: "Fatick" },
      { name: "Kolda" },
      { name: "Tambacounda" },
    ],
  },
  {
    id: "155",
    name: "Serbia",
    code: "RS",
    phonePrefix: "+381",
    flag: "🇷🇸",
    currency: "RSD",
  },
  {
    id: "156",
    name: "Seychelles",
    code: "SC",
    phonePrefix: "+248",
    flag: "🇸🇨",
    currency: "SCR",
  },
  {
    id: "157",
    name: "Sierra Leone",
    code: "SL",
    phonePrefix: "+232",
    flag: "🇸🇱",
    currency: "SLL",
  },
  {
    id: "158",
    name: "Singapore",
    code: "SG",
    phonePrefix: "+65",
    flag: "🇸🇬",
    currency: "SGD",
  },
  {
    id: "159",
    name: "Slovakia",
    code: "SK",
    phonePrefix: "+421",
    flag: "🇸🇰",
    currency: "EUR",
  },
  {
    id: "160",
    name: "Slovenia",
    code: "SI",
    phonePrefix: "+386",
    flag: "🇸🇮",
    currency: "EUR",
  },
  {
    id: "161",
    name: "Solomon Islands",
    code: "SB",
    phonePrefix: "+677",
    flag: "🇸🇧",
    currency: "SBD",
  },
  {
    id: "162",
    name: "Somalia",
    code: "SO",
    phonePrefix: "+252",
    flag: "🇸🇴",
    currency: "SOS",
  },
  {
    id: "163",
    name: "South Africa",
    code: "ZA",
    phonePrefix: "+27",
    flag: "🇿🇦",
    currency: "ZAR",
  },
  {
    id: "164",
    name: "South Sudan",
    code: "SS",
    phonePrefix: "+211",
    flag: "🇸🇸",
    currency: "SSP",
  },
  {
    id: "165",
    name: "Spain",
    code: "ES",
    phonePrefix: "+34",
    flag: "🇪🇸",
    currency: "EUR",
  },
  {
    id: "166",
    name: "Sri Lanka",
    code: "LK",
    phonePrefix: "+94",
    flag: "🇱🇰",
    currency: "LKR",
  },
  {
    id: "167",
    name: "Sudan",
    code: "SD",
    phonePrefix: "+249",
    flag: "🇸🇩",
    currency: "SDG",
  },
  {
    id: "168",
    name: "Suriname",
    code: "SR",
    phonePrefix: "+597",
    flag: "🇸🇷",
    currency: "SRD",
  },
  {
    id: "169",
    name: "Sweden",
    code: "SE",
    phonePrefix: "+46",
    flag: "🇸🇪",
    currency: "SEK",
  },
  {
    id: "170",
    name: "Switzerland",
    code: "CH",
    phonePrefix: "+41",
    flag: "🇨🇭",
    currency: "CHF",
  },
  {
    id: "171",
    name: "Syria",
    code: "SY",
    phonePrefix: "+963",
    flag: "🇸🇾",
    currency: "SYP",
  },
  {
    id: "172",
    name: "Taiwan",
    code: "TW",
    phonePrefix: "+886",
    flag: "🇹🇼",
    currency: "TWD",
  },
  {
    id: "173",
    name: "Tajikistan",
    code: "TJ",
    phonePrefix: "+992",
    flag: "🇹🇯",
    currency: "TJS",
  },
  {
    id: "174",
    name: "Tanzania",
    code: "TZ",
    phonePrefix: "+255",
    flag: "🇹🇿",
    currency: "TZS",
  },
  {
    id: "175",
    name: "Thailand",
    code: "TH",
    phonePrefix: "+66",
    flag: "🇹🇭",
    currency: "THB",
  },
  {
    id: "176",
    name: "Togo",
    code: "TG",
    phonePrefix: "+228",
    flag: "🇹🇬",
    currency: "XOF",
    cities: [
      { name: "Lomé", communes: ["Golfe", "Agoe-Nyive", "Lacs", "Vo", "Yoto"] },
      { name: "Sokodé", communes: ["Sokodé Centre", "Sokodé Nord"] },
      { name: "Kara", communes: ["Kara Centre", "Kara Nord"] },
      { name: "Atakpamé", communes: ["Atakpamé Centre", "Atakpamé Nord"] },
      { name: "Dapaong" },
      { name: "Tsévié" },
      { name: "Aného" },
      { name: "Bassar" },
    ],
  },
  {
    id: "177",
    name: "Tonga",
    code: "TO",
    phonePrefix: "+676",
    flag: "🇹🇴",
    currency: "TOP",
  },
  {
    id: "178",
    name: "Trinidad and Tobago",
    code: "TT",
    phonePrefix: "+1-868",
    flag: "🇹🇹",
    currency: "TTD",
  },
  {
    id: "179",
    name: "Tunisia",
    code: "TN",
    phonePrefix: "+216",
    flag: "🇹🇳",
    currency: "TND",
  },
  {
    id: "180",
    name: "Turkey",
    code: "TR",
    phonePrefix: "+90",
    flag: "🇹🇷",
    currency: "TRY",
  },
  {
    id: "181",
    name: "Turkmenistan",
    code: "TM",
    phonePrefix: "+993",
    flag: "🇹🇲",
    currency: "TMT",
  },
  {
    id: "182",
    name: "Tuvalu",
    code: "TV",
    phonePrefix: "+688",
    flag: "🇹🇻",
    currency: "AUD",
  },
  {
    id: "183",
    name: "Uganda",
    code: "UG",
    phonePrefix: "+256",
    flag: "🇺🇬",
    currency: "UGX",
  },
  {
    id: "184",
    name: "Ukraine",
    code: "UA",
    phonePrefix: "+380",
    flag: "🇺🇦",
    currency: "UAH",
  },
  {
    id: "185",
    name: "United Arab Emirates",
    code: "AE",
    phonePrefix: "+971",
    flag: "🇦🇪",
    currency: "AED",
  },
  {
    id: "186",
    name: "United Kingdom",
    code: "GB",
    phonePrefix: "+44",
    flag: "🇬🇧",
    currency: "GBP",
  },
  {
    id: "187",
    name: "United States",
    code: "US",
    phonePrefix: "+1",
    flag: "🇺🇸",
    currency: "USD",
  },
  {
    id: "188",
    name: "Uruguay",
    code: "UY",
    phonePrefix: "+598",
    flag: "🇺🇾",
    currency: "UYU",
  },
  {
    id: "189",
    name: "Uzbekistan",
    code: "UZ",
    phonePrefix: "+998",
    flag: "🇺🇿",
    currency: "UZS",
  },
  {
    id: "190",
    name: "Vanuatu",
    code: "VU",
    phonePrefix: "+678",
    flag: "🇻🇺",
    currency: "VUV",
  },
  {
    id: "191",
    name: "Vatican City",
    code: "VA",
    phonePrefix: "+379",
    flag: "🇻🇦",
    currency: "EUR",
  },
  {
    id: "192",
    name: "Venezuela",
    code: "VE",
    phonePrefix: "+58",
    flag: "🇻🇪",
    currency: "VES",
  },
  {
    id: "193",
    name: "Vietnam",
    code: "VN",
    phonePrefix: "+84",
    flag: "🇻🇳",
    currency: "VND",
  },
  {
    id: "194",
    name: "Yemen",
    code: "YE",
    phonePrefix: "+967",
    flag: "🇾🇪",
    currency: "YER",
  },
  {
    id: "195",
    name: "Zambia",
    code: "ZM",
    phonePrefix: "+260",
    flag: "🇿🇲",
    currency: "ZMW",
  },
  {
    id: "196",
    name: "Zimbabwe",
    code: "ZW",
    phonePrefix: "+263",
    flag: "🇿🇼",
    currency: "ZWL",
  },
];

// Helper functions
export const getCountryByCode = (code: string): Country | undefined => {
  return ALL_COUNTRIES.find((country) => country.code === code);
};

export const getCountryByName = (name: string): Country | undefined => {
  return ALL_COUNTRIES.find(
    (country) => country.name.toLowerCase() === name.toLowerCase()
  );
};

export const getCitiesByCountryCode = (countryCode: string): City[] => {
  const country = getCountryByCode(countryCode);
  return country?.cities || [];
};

export const getCommunesByCity = (
  countryCode: string,
  cityName: string
): string[] => {
  const cities = getCitiesByCountryCode(countryCode);
  const city = cities.find(
    (c) => c.name.toLowerCase() === cityName.toLowerCase()
  );
  return city?.communes || [];
};

export const getCountryNames = (): string[] => {
  return ALL_COUNTRIES.map((country) => country.name);
};

export const getPhonePrefixes = (): { [key: string]: string } => {
  const prefixes: { [key: string]: string } = {};
  ALL_COUNTRIES.forEach((country) => {
    prefixes[country.code] = country.phonePrefix;
  });
  return prefixes;
};
