// Constantes pour les véhicules de transport

export const VEHICLE_BRANDS = [
  {
    id: "mercedes",
    name: "Mercedes-Benz",
    logo: "🚌",
    models: [
      "Sprinter",
      "Tourismo",
      "Travego",
      "Citaro",
      "eCitaro",
      "Conecto",
      "Integro",
      "Intouro",
      "Setra S 415",
      "Setra S 516",
      "Setra S 531",
      "O 500",
      "Atego",
      "Axor",
    ],
  },
  {
    id: "volvo",
    name: "Volvo",
    logo: "🚐",
    models: [
      "9700",
      "9900",
      "8700",
      "7900",
      "B8R",
      "B11R",
      "B12B",
      "B13R",
      "FH",
      "FM",
      "FMX",
      "Sunsundegui",
      "Plaxton Elite",
    ],
  },
  {
    id: "scania",
    name: "Scania",
    logo: "🚌",
    models: [
      "Touring",
      "Interlink",
      "Citywide",
      "Omnilink",
      "OmniExpress",
      "Irizar i6",
      "Irizar i8",
      "K-series",
      "P-series",
      "G-series",
      "R-series",
    ],
  },
  {
    id: "man",
    name: "MAN",
    logo: "🚐",
    models: [
      "Lion's Coach",
      "Lion's City",
      "Lion's Intercity",
      "Lion's Regio",
      "TGE",
      "TGM",
      "TGS",
      "TGX",
      "Neoplan Tourliner",
      "Neoplan Cityliner",
    ],
  },
  {
    id: "iveco",
    name: "Iveco",
    logo: "🚌",
    models: [
      "Daily",
      "Eurocargo",
      "Stralis",
      "Trakker",
      "Crossway",
      "Evadys",
      "Magelys",
      "Urbanway",
      "Crealis",
    ],
  },
  {
    id: "isuzu",
    name: "Isuzu",
    logo: "🚐",
    models: [
      "NPR",
      "NQR",
      "FRR",
      "FVR",
      "CXZ",
      "Giga",
      "Forward",
      "Elf",
      "D-Max",
      "Novociti Life",
    ],
  },
  {
    id: "toyota",
    name: "Toyota",
    logo: "🚐",
    models: [
      "Hiace",
      "Coaster",
      "Dyna",
      "Hino",
      "Land Cruiser",
      "Prado",
      "Fortuner",
      "Commuter",
    ],
  },
  {
    id: "ford",
    name: "Ford",
    logo: "🚐",
    models: [
      "Transit",
      "Transit Custom",
      "E-Transit",
      "Tourneo",
      "Ranger",
      "F-Series",
      "Econoline",
    ],
  },
  {
    id: "renault",
    name: "Renault",
    logo: "🚐",
    models: [
      "Master",
      "Trafic",
      "Kangoo",
      "D-series",
      "T-series",
      "K-series",
      "Midlum",
      "Premium",
    ],
  },
  {
    id: "peugeot",
    name: "Peugeot",
    logo: "🚐",
    models: ["Boxer", "Expert", "Partner", "Traveller", "e-Boxer", "e-Expert"],
  },
  {
    id: "fiat",
    name: "Fiat",
    logo: "🚐",
    models: ["Ducato", "Scudo", "Doblo", "Talento", "e-Ducato", "Fiorino"],
  },
  {
    id: "volkswagen",
    name: "Volkswagen",
    logo: "🚐",
    models: [
      "Crafter",
      "Caddy",
      "Transporter",
      "Caravelle",
      "Multivan",
      "ID.Buzz",
      "LT",
      "Amarok",
    ],
  },
  {
    id: "hyundai",
    name: "Hyundai",
    logo: "🚐",
    models: [
      "H350",
      "H-1",
      "Starex",
      "County",
      "Universe",
      "Aero",
      "Super Aero",
    ],
  },
  {
    id: "king_long",
    name: "King Long",
    logo: "🚌",
    models: ["XMQ6127", "XMQ6129", "XMQ6130", "XMQ6900", "XMQ6800", "Higer"],
  },
  {
    id: "yutong",
    name: "Yutong",
    logo: "🚌",
    models: ["ZK6127H", "ZK6129H", "ZK6122H", "ZK6118H", "ZK6107H", "E-series"],
  },
];

export const VEHICLE_COLORS = [
  { id: "white", name: "Blanc", hex: "#FFFFFF", textColor: "#000000" },
  { id: "black", name: "Noir", hex: "#000000", textColor: "#FFFFFF" },
  { id: "silver", name: "Argent", hex: "#C0C0C0", textColor: "#000000" },
  { id: "gray", name: "Gris", hex: "#808080", textColor: "#FFFFFF" },
  { id: "red", name: "Rouge", hex: "#FF0000", textColor: "#FFFFFF" },
  { id: "blue", name: "Bleu", hex: "#0000FF", textColor: "#FFFFFF" },
  { id: "navy", name: "Bleu Marine", hex: "#000080", textColor: "#FFFFFF" },
  { id: "green", name: "Vert", hex: "#008000", textColor: "#FFFFFF" },
  { id: "yellow", name: "Jaune", hex: "#FFFF00", textColor: "#000000" },
  { id: "orange", name: "Orange", hex: "#FFA500", textColor: "#000000" },
  { id: "purple", name: "Violet", hex: "#800080", textColor: "#FFFFFF" },
  { id: "brown", name: "Marron", hex: "#8B4513", textColor: "#FFFFFF" },
  { id: "gold", name: "Doré", hex: "#FFD700", textColor: "#000000" },
  { id: "beige", name: "Beige", hex: "#F5F5DC", textColor: "#000000" },
  { id: "cream", name: "Crème", hex: "#FFFDD0", textColor: "#000000" },
  { id: "burgundy", name: "Bordeaux", hex: "#800020", textColor: "#FFFFFF" },
  { id: "teal", name: "Sarcelle", hex: "#008080", textColor: "#FFFFFF" },
  { id: "lime", name: "Vert Lime", hex: "#00FF00", textColor: "#000000" },
  { id: "pink", name: "Rose", hex: "#FFC0CB", textColor: "#000000" },
  { id: "turquoise", name: "Turquoise", hex: "#40E0D0", textColor: "#000000" },
];

export const VEHICLE_YEARS = Array.from(
  { length: new Date().getFullYear() - 1987 + 1 },
  (_, i) => ({
    id: (1987 + i).toString(),
    name: (1987 + i).toString(),
    value: 1987 + i,
  })
).reverse(); // Les années les plus récentes en premier

export const VEHICLE_TYPES = [
  { id: "minibus", name: "Minibus", capacity: "8-15 places", icon: "🚐" },
  { id: "bus", name: "Bus", capacity: "16-35 places", icon: "🚌" },
  {
    id: "coach",
    name: "Car de tourisme",
    capacity: "36-55 places",
    icon: "🚍",
  },
  {
    id: "luxury_bus",
    name: "Bus de luxe",
    capacity: "20-45 places",
    icon: "🚌",
  },
  {
    id: "double_decker",
    name: "Bus à étage",
    capacity: "60-80 places",
    icon: "🚌",
  },
  {
    id: "articulated",
    name: "Bus articulé",
    capacity: "80-120 places",
    icon: "🚌",
  },
  { id: "van", name: "Fourgonnette", capacity: "4-8 places", icon: "🚐" },
  { id: "truck", name: "Camion", capacity: "Marchandises", icon: "🚛" },
];

export const FUEL_TYPES = [
  { id: "diesel", name: "Diesel", icon: "⛽" },
  { id: "gasoline", name: "Essence", icon: "⛽" },
  { id: "electric", name: "Électrique", icon: "🔋" },
  { id: "hybrid", name: "Hybride", icon: "🔋" },
  { id: "cng", name: "GNC (Gaz Naturel)", icon: "💨" },
  { id: "lpg", name: "GPL (Gaz de Pétrole)", icon: "💨" },
];
